// Launchpad app registry
// In production, this will be backed by Supabase
// For now, it's a simple in-memory config that can be populated by Launchpad

// Example app structure - will be generated by Launchpad
const APPS = {
  // Example: This would be generated when creating an app
  // "invoice-nudge": {
  //   slug: "invoice-nudge",
  //   name: "Invoice Nudge",
  //   tagline: "Get paid without the awkward follow-ups",
  //   description: "Automated invoice reminders that sound like you",
  //   audience: "Freelancers & consultants",
  //   color: "#0ea5e9",
  //   status: "active", // active, building, archived
  //   createdAt: "2026-02-08",
  //   landing: {
  //     headline: "Stop chasing payments. Start getting paid.",
  //     problem: "Late invoices kill cash flow. Chasing clients is awkward and time-consuming.",
  //     solution: "Automated reminders that sound like you wrote them. Set it and forget it.",
  //     features: [
  //       { icon: "⏰", title: "Smart Scheduling", description: "Reminders go out at optimal times" },
  //       { icon: "💬", title: "Your Voice", description: "Customizable tone that matches your style" },
  //       { icon: "📊", title: "Payment Tracking", description: "See what's paid, pending, and overdue" },
  //     ],
  //     cta: "Join the Waitlist",
  //   },
  //   infrastructure: {
  //     auth: true,
  //     feedback: true,
  //     onboarding: true,
  //     payments: false,
  //   },
  //   meta: {
  //     title: "Invoice Nudge - Get Paid Without the Awkward Follow-ups",
  //     description: "Automated invoice reminders for freelancers. Stop chasing payments.",
  //     ogImage: "/og/invoice-nudge.png",
  //   },
  // },
};

/**
 * Get app configuration by slug
 * @param {string} slug - The app slug (e.g., "invoice-nudge")
 * @returns {object|null} - App config or null if not found
 */
export function getApp(slug) {
  return APPS[slug] || null;
}

/**
 * Get all apps
 * @returns {object[]} - Array of all app configs
 */
export function getAllApps() {
  return Object.values(APPS);
}

/**
 * Register a new app (called by Launchpad during generation)
 * @param {object} appConfig - The app configuration
 */
export function registerApp(appConfig) {
  APPS[appConfig.slug] = {
    ...appConfig,
    createdAt: new Date().toISOString(),
    status: "active",
  };
}

/**
 * Check if an app exists
 * @param {string} slug - The app slug
 * @returns {boolean}
 */
export function appExists(slug) {
  return slug in APPS;
}

// Export the apps object for direct access if needed
export { APPS };
