-- Launchpad Database Schema
-- Run this in Supabase SQL Editor to set up the required tables

-- ============================================
-- LAUNCHPAD APPS TABLE
-- Stores all apps generated by Launchpad
-- ============================================
CREATE TABLE IF NOT EXISTS launchpad_apps (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug VARCHAR(100) UNIQUE NOT NULL,
  name VARCHAR(255) NOT NULL,
  tagline VARCHAR(500),
  description TEXT,
  audience VARCHAR(255),
  icon VARCHAR(10),
  color VARCHAR(20) DEFAULT '#0ea5e9',
  status VARCHAR(50) DEFAULT 'active', -- active, building, archived, deleted

  -- Landing page content (JSON)
  landing JSONB DEFAULT '{}'::jsonb,
  -- { headline, problem, solution, features: [{icon, title, description}], cta }

  -- Infrastructure flags
  infrastructure JSONB DEFAULT '{"auth": true, "feedback": true, "onboarding": true, "payments": false}'::jsonb,

  -- OG metadata
  meta JSONB DEFAULT '{}'::jsonb,
  -- { title, description, ogImage }

  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  published_at TIMESTAMPTZ,

  -- Owner (for future multi-tenancy)
  owner_id VARCHAR(255)
);

-- Index for quick slug lookups
CREATE INDEX IF NOT EXISTS idx_launchpad_apps_slug ON launchpad_apps(slug);
CREATE INDEX IF NOT EXISTS idx_launchpad_apps_status ON launchpad_apps(status);

-- ============================================
-- FEEDBACK TABLE
-- Collects user feedback across all apps
-- ============================================
CREATE TABLE IF NOT EXISTS feedback (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  app_slug VARCHAR(100) NOT NULL,

  -- Feedback content
  message TEXT NOT NULL,
  type VARCHAR(50) DEFAULT 'general', -- general, bug, feature, praise

  -- Context
  page_url VARCHAR(500),
  user_agent TEXT,

  -- User info (optional, may be anonymous)
  user_id VARCHAR(255),
  user_email VARCHAR(255),

  -- Status
  status VARCHAR(50) DEFAULT 'new', -- new, reviewed, resolved, archived

  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW(),
  reviewed_at TIMESTAMPTZ,

  -- Foreign key to apps table
  CONSTRAINT fk_feedback_app FOREIGN KEY (app_slug)
    REFERENCES launchpad_apps(slug) ON DELETE CASCADE
);

-- Indexes for feedback queries
CREATE INDEX IF NOT EXISTS idx_feedback_app_slug ON feedback(app_slug);
CREATE INDEX IF NOT EXISTS idx_feedback_status ON feedback(status);
CREATE INDEX IF NOT EXISTS idx_feedback_created_at ON feedback(created_at DESC);

-- ============================================
-- WAITLIST TABLE
-- Tracks waitlist signups per app
-- ============================================
CREATE TABLE IF NOT EXISTS waitlist (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  app_slug VARCHAR(100) NOT NULL,

  email VARCHAR(255) NOT NULL,

  -- Source tracking
  source VARCHAR(100), -- twitter, linkedin, direct, referral
  referrer_url VARCHAR(500),
  utm_source VARCHAR(100),
  utm_medium VARCHAR(100),
  utm_campaign VARCHAR(100),

  -- Status
  status VARCHAR(50) DEFAULT 'pending', -- pending, welcomed, converted, unsubscribed
  welcomed_at TIMESTAMPTZ,

  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW(),

  -- Unique per app
  UNIQUE(app_slug, email)
);

-- Indexes for waitlist queries
CREATE INDEX IF NOT EXISTS idx_waitlist_app_slug ON waitlist(app_slug);
CREATE INDEX IF NOT EXISTS idx_waitlist_email ON waitlist(email);
CREATE INDEX IF NOT EXISTS idx_waitlist_created_at ON waitlist(created_at DESC);

-- ============================================
-- ONBOARDING PROGRESS TABLE
-- Tracks user progress through onboarding steps
-- ============================================
CREATE TABLE IF NOT EXISTS onboarding_progress (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  app_slug VARCHAR(100) NOT NULL,
  user_id VARCHAR(255) NOT NULL,

  -- Progress tracking
  current_step INT DEFAULT 0,
  completed_steps INT[] DEFAULT ARRAY[]::INT[],
  is_complete BOOLEAN DEFAULT FALSE,
  skipped BOOLEAN DEFAULT FALSE,

  -- Timestamps
  started_at TIMESTAMPTZ DEFAULT NOW(),
  completed_at TIMESTAMPTZ,
  last_activity_at TIMESTAMPTZ DEFAULT NOW(),

  -- Unique per user per app
  UNIQUE(app_slug, user_id)
);

-- Index for onboarding lookups
CREATE INDEX IF NOT EXISTS idx_onboarding_app_user ON onboarding_progress(app_slug, user_id);

-- ============================================
-- ROW LEVEL SECURITY (RLS)
-- Enable for production use
-- ============================================
-- ALTER TABLE launchpad_apps ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE feedback ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE waitlist ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE onboarding_progress ENABLE ROW LEVEL SECURITY;

-- ============================================
-- UPDATED_AT TRIGGER
-- Auto-update the updated_at timestamp
-- ============================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_launchpad_apps_updated_at
  BEFORE UPDATE ON launchpad_apps
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();
